### ISSUE TITLE
Question about that packetData.

### ISSUE THREAD

**Issue by SzaszSzilard** [sebastienwarin/Knock#1]
Hy, sorry for bothering you, but i really don't know where did you get that long packetData.
Could you explain it please :)?

**Comment by SeppPenner** [comment]
You know that you can change the package data based on your configuration, don't you? I mean, the package data depends on your firewall roule inside the server you want to knock on...

**Comment by SeppPenner** [comment]
By the way, i have enhanced the client a bit. Take a look at https://github.com/SeppPenner/PortKnocker :)

**Comment by SzaszSzilard** [comment]
Thank you for yor answer. In the end I just ended up sending some empty packets if i remember correctly. Now i ve been using for years. Still works lie a charm. Later i am gona check out your solution as well ;)

**Comment by SeppPenner** [comment]
> In the end I just ended up sending some empty packets if i remember correctly.

This is not really the sense of the package data. I mean, port knocking without the package data is useless? An attacker could test your server and simply send empty packages to all ports from 0 to 65535...

**Comment by SzaszSzilard** [comment]
Well. Our knock to be succesful we need several ports knocked in a specific order. If the order is not met then the knock wont be succesful. I didn't realized that some servers just use a single knock but with packet data. Thank you for shining some light on that ;)

**Comment by SeppPenner** [comment]
Ah, I see. This is a very clever idea :D This is something that would have never come to my mind :) 👍
